### ISSUE TITLE
fsm.Data 锁使用 BUG 太多

### ISSUE THREAD

**Issue by fananchong** [vision9527/raft-demo#1]
虽然是例子，但是也要保证代码没 BUG 

特别是 review 代码一眼可以看出来的 BUG 不能有

fsm.Data 以下函数有锁使用问题：

- HttpServer.Get 函数中未对 fsm.Data 加锁
- Fsm.Snapshot 函数加锁没意义
- database.Persist 函数未加锁

**Comment by vision9527** [comment]
好的，已修改
